version: "3.3"

services:
  express:
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/api.dockerfile
    image: db-api-gateway:v1
    env_file:
      - ./.env
    ports:
      - "${PORT}:8080"
    container_name: ${APP_CONTAINER_NAME}
    hostname: ${APP_CONTAINER_NAME}
    command: ./node_modules/.bin/ts-node --esm src/index.ts
    volumes:
      - .:/code